[theme]
base="dark"

# ---- Main area ----
primaryColor="#268bd2"              # Solarized blue for highlights
backgroundColor="#002b36"           # Base03: very dark cyan
textColor="#93a1a1"                 # Base1: light grey-cyan
font="monospace"

# ---- Sidebar variation ----
secondaryBackgroundColor="#073642"  # Base02: slightly lighter, for sidebar contrast

[global]
developmentMode = false
showWarningOnDirectExecution = true

[logger]
level = "warning"
messageFormat = "%(asctime)s %(message)s"

[server]
port = 8501
folderWatchBlacklist = []

# If XSRF protection is enabled and CORS protection is disabled at the
# same time, Streamlit will enable them both instead.
# Default: true
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for
# added security.
# If XSRF protection is enabled and CORS protection is disabled at the
# same time, Streamlit will enable them both instead.
# Default: true
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 150

fileWatcherType = "none"

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 150

# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = false

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false

# Internet address of the server that the browser should connect to. Can be IP address or DNS name.
# Default: 'localhost'
# serverAddress = "0.0.0.0"

[client]
# Default: "full"
showErrorDetails = "minimal"

# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).
# Allowed values:
# - "auto"      : Show the developer options if the app is accessed through
#                 localhost or through Streamlit Community Cloud as a developer.
#                 Hide them otherwise.
# - "developer" : Show the developer options.
# - "viewer"    : Hide the developer options.
# - "minimal"   : Show only options set externally (e.g. through
#                 Streamlit Community Cloud) or through st.set_page_config.
#                 If there are no options left, hide the menu.
# Default: "auto"
toolbarMode = "minimal"

# Controls whether to display the default sidebar page navigation in a
# multi-page app. This only applies when app's pages are defined by the
# `pages/` directory.
# Default: true
showSidebarNavigation = false
