[theme]
base = "dark"
primaryColor = "#268bd2"               # Solarized blue
backgroundColor = "#002b36"             # App main background
secondaryBackgroundColor = "#073642"    # Widget background
textColor = "#839496"                   # Main text
linkColor = "#2aa198"                   # Links
codeBackgroundColor = "#073642"          # Code blocks

# Font settings
font = "sans-serif"                     # For normal text
codeFont = "Source Code Pro, monospace"  # For code
headingFont = "sans-serif"               # For headings

# Visual Tweaks
baseRadius = "0.5rem"                    # Rounded elements
borderColor = "#586e75"                  # Subtle border
showWidgetBorder = true
baseFontSize = 16
showSidebarBorder = false                # No hard sidebar border


# Specific colors for sidebar
[theme.sidebar]
backgroundColor = "#001a22"             # Slightly darker than page background
textColor = "#839496"                   # Same text color
borderColor = "#586e75"                 # Subtle border if needed


[global]
developmentMode = false
showWarningOnDirectExecution = true

[logger]
level = "debug"
messageFormat = "%(asctime)s %(message)s"

[server]
port = 80
folderWatchBlacklist = ['']

# If XSRF protection is enabled and CORS protection is disabled at the
# same time, Streamlit will enable them both instead.
# Default: true
enableCORS = true

# Enables support for Cross-Site Request Forgery (XSRF) protection, for
# added security.
# If XSRF protection is enabled and CORS protection is disabled at the
# same time, Streamlit will enable them both instead.
# Default: true
enableXsrfProtection = true

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 100

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 200

# Immediately share the app in such a way that enables live monitoring, and post-run analysis.
# Default: false
liveSave = false

# Automatically rerun script when the file is modified on disk.
# Default: false
runOnSave = false

[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false

# Internet address of the server that the browser should connect to. Can be IP address or DNS name.
# Default: 'localhost'
serverAddress = "0.0.0.0"


[client]
# Controls whether uncaught app exceptions and deprecation warnings
# are displayed in the browser. This can be one of the following:
# - "full"       : In the browser, Streamlit displays app deprecation
#                  warnings and exceptions, including exception types,
#                  exception messages, and associated tracebacks.
# - "stacktrace" : In the browser, Streamlit displays exceptions,
#                  including exception types, generic exception messages,
#                  and associated tracebacks. Deprecation warnings and
#                  full exception messages will only print to the
#                  console.
# - "type"       : In the browser, Streamlit displays exception types and
#                  generic exception messages. Deprecation warnings, full
#                  exception messages, and associated tracebacks only
#                  print to the console.
# - "none"       : In the browser, Streamlit displays generic exception
#                  messages. Deprecation warnings, full exception
#                  messages, associated tracebacks, and exception types
#                  will only print to the console.
# - True         : This is deprecated. Streamlit displays "full"
#                  error details.
# - False        : This is deprecated. Streamlit displays "stacktrace"
#                  error details.
# Default: "full"
showErrorDetails = "full"

# Change the visibility of items in the toolbar, options menu,
# and settings dialog (top right of the app).
# Allowed values:
# - "auto"      : Show the developer options if the app is accessed through
#                 localhost or through Streamlit Community Cloud as a developer.
#                 Hide them otherwise.
# - "developer" : Show the developer options.
# - "viewer"    : Hide the developer options.
# - "minimal"   : Show only options set externally (e.g. through
#                 Streamlit Community Cloud) or through st.set_page_config.
#                 If there are no options left, hide the menu.
# Default: "auto"
toolbarMode = "viewer"

# Controls whether to display the default sidebar page navigation in a
# multi-page app. This only applies when app's pages are defined by the
# `pages/` directory.
# Default: true
showSidebarNavigation = false
